export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';
export const CHANGE_TIMEDATEFIELD = 'CHANGE_TIMEDATEFIELD';

export const REQUEST_FLIGHTS_PENDING = 'REQUEST_FLIGHTS_PENDING';
export const REQUEST_FLIGHTS_SUCCESS = 'REQUEST_FLIGHTS_SUCCESS';
export const REQUEST_FLIGHTS_FAILED = 'REQUEST_FLIGHTS_FAILED';
